---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.4.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 5.3.3" STRICT_VARIABLES=yes
matrix:
  include:
    - rvm: '2.4'
      sudo: required
      services: docker
      env: BEAKER_set="ubuntu-server-1704-docker" PUPPET_INSTALL_TYPE=foss
      script: bundle exec rspec spec/acceptance/travis_ci_acceptance_spec.rb
      bundler_args: --without development
    - rvm: '2.4'
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-docker" PUPPET_INSTALL_TYPE=foss
      script: bundle exec rspec spec/acceptance/travis_ci_acceptance_spec.rb
      bundler_args: --without development
